"""Restore the stage-(g) stamp for references whose BUILD DIRECTORY was lost.

WHY THIS EXISTS. `benchmark/witness_build/` disappeared on 2026-08-18 (cause
unknown; see docs/rung0-results.md). Grading a candidate needs two things from that
directory, and only one of them was expensive:

  * `harness.cpp`, which embeds the golden vectors -- generated by PyTorch on the
    HOST (`run_batch` stages `golden`/`harness`, before any simulator), ~14 s for a
    whole batch via `run_batch --skip-verify`. Cheap, and fully regenerable.
  * `results.json`, recording that the reference kernel PASSED that harness in the
    simulator -- stage (g). That is the multi-day part, and re-running it re-derives
    an answer already on record.

WHAT IT ASSERTS, AND ON WHAT EVIDENCE. Every rung-0 attempt record carries
`grade.reference_verified`, stamped by `grade_one` at the time it graded against a
reference that `evalset.reference_status` had reported verified. So the fact "this
reference passed stage (g)" is recorded in `runs/`, which survived. This script
copies that recorded fact back into the file `reference_status` reads. It REFUSES to
invent one: no stamp in the records, no restoration.

WHY THE STAMP TRANSFERS TO A REGENERATED HARNESS. It only transfers if the harness
came back identical, and that was verified rather than assumed:

  * The generator has not changed. `hexforge/frontend/`, `mined.py`, `kernels.py`
    and `coverage.py` are untouched since 2026-08-11, before the run; torch is the
    same 2.7.1+cu128 recorded in `benchmark/environment.json`; and two regenerations
    of one batch produced byte-identical `harness.cpp`.
  * MEASURED on batch 27: five recorded candidates re-run against the REGENERATED
    harness reproduced their recorded instruction counts EXACTLY, 5/5 (14356, 14430,
    14359, 60195, 60195). insns counts every instruction the program executes, so an
    exact match on five different candidates is not a coincidence of tolerance.
  * The spec reproduces for every task in the batches restored here: the rung-0
    prompt is built from the artifact's signature and graph, and its sha256 matches
    the hash recorded in all 25 attempt records across batches 48/57/69/72/74 --
    including batch 48, which `mined.py` records as having had a shape-plan bug.

A pitfall worth knowing, because it made the first check look like a failure:
`insns` DEPENDS ON THE ELF FILENAME. `verify(name=...)` names the binary, the
simulator is invoked with that path, and startup walks argv -- so a shorter name
reads ~18 instructions lower per character dropped. Comparing against a recorded
count requires the grader's own `name=f"{ref.key}_s{seed}"`. A constant -396 across
five candidates was that, not a harness difference.

WHAT IS DELIBERATELY NOT CLAIMED. The restored entry is marked `restored: true` with
its evidence, and carries `insns: null` / `pcycles: null` -- the reference's OWN
cycle counts were never recorded per attempt and are not guessed. Nothing may read a
restored entry as a fresh execution. Re-run `run_batch --batch N` without
`--skip-verify` to replace it with a real one.

    python scripts/restore_reference_stamp.py --model gpt-5.6-luna \
        --only b48i0_fp16_linear,b57i0_fp16_scaled_dot_product_attention [--apply]
"""
import argparse
import datetime
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from hexforge import evalset  # noqa: E402

EVIDENCE = ("stage-(g) stamp recorded in runs/<model>/attempts.jsonl "
            "(grade.reference_verified); harness regenerated by "
            "run_batch --skip-verify and confirmed faithful by exact insns "
            "reproduction on batch 27 (5/5) and by matching rung-0 prompt "
            "sha256 for every task in the restored batches")


def stamps_for(model: str, root=pathlib.Path("runs")) -> dict:
    """`{task key: True}` for every task some attempt graded against a live ref.

    Read from the merged record rather than the per-attempt files because the merged
    one is what git tracks -- the per-attempt `attempt.json` files are not committed.
    """
    path = root / "rung0" / model / "attempts.jsonl"
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if (r.get("grade") or {}).get("reference_verified"):
                out[r["task"]["key"]] = True
    return out


def restored_verdict(stamps: dict, ref) -> dict:
    """The `reference` entry to write, or raise if nothing recorded it as passing."""
    if not stamps.get(ref.key):
        raise LookupError(
            f"{ref.key}: no attempt record carries reference_verified, so there is "
            "no recorded stage-(g) pass to restore. Build it for real: "
            f"python -m hexforge.run_batch --batch {ref.batch} "
            f"--out benchmark/witness_build/batch{ref.batch}")
    return {"compiled": True, "ran": True, "correct": True, "timing": False,
            "insns": None, "pcycles": None, "mechanisms": {},
            "restored": True, "restored_at": datetime.datetime.now(
                datetime.timezone.utc).replace(microsecond=0).isoformat(),
            "restored_evidence": EVIDENCE}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", required=True)
    ap.add_argument("--only", required=True,
                    help="comma-separated task keys, as `rung0 --only` takes")
    ap.add_argument("--apply", action="store_true",
                    help="write; without it, report what would change")
    args = ap.parse_args(argv)

    tasks, _ = evalset.core_tasks()
    wanted = set(args.only.split(","))
    picked = [t for t in tasks if t.key in wanted]
    missing = wanted - {t.key for t in picked}
    if missing:
        print(f"not in the eval core: {sorted(missing)}", file=sys.stderr)
        return 2

    stamps = stamps_for(args.model)
    changed = 0
    for ref in picked:
        res = pathlib.Path(evalset.WITNESS) / f"batch{ref.batch}" / "results.json"
        if not res.exists():
            print(f"  {ref.key}: no results.json -- regenerate the batch first "
                  f"(run_batch --batch {ref.batch} --skip-verify)", file=sys.stderr)
            return 2
        try:
            verdict = restored_verdict(stamps, ref)
        except LookupError as exc:
            print(f"  REFUSED {exc}", file=sys.stderr)
            return 2
        doc = json.loads(res.read_text(encoding="utf-8"))
        was = (doc.get("reference") or {}).get(ref.name, {}).get("correct")
        print(f"  batch {ref.batch:3d} {ref.name:45s} correct {was} -> True")
        if args.apply:
            doc.setdefault("reference", {})[ref.name] = verdict
            res.write_text(json.dumps(doc, indent=2, sort_keys=True, default=str),
                           encoding="utf-8")
        changed += 1

    print(f"\n{'restored' if args.apply else 'would restore'} {changed} reference "
          f"stamp(s)")
    if args.apply:
        for ref in picked:
            st = evalset.reference_status(ref)
            print(f"  {ref.key:50s} verified={st['verified']} "
                  f"{st['reason']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
